services:
  kaggle:
    build: .
    volumes:
      - $PWD/.jupyter:/root/.jupyter
      - $PWD/input:/kaggle/input
      - $PWD/.cache:/root/.cache
      - $PWD:/kaggle/working
    environment:
      - JUPYTERLAB_SETTINGS_DIR=/kaggle/working/.jupyter-settings
      - NETRC=/kaggle/working/.netrc
    working_dir: /kaggle/working
    ports:
      - 8889:8889
    command: jupyter lab --allow-root --ip=0.0.0.0 --port=8889 --no-browser --NotebookApp.token=''
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: "8gb"
